### PR TITLE
Update to deis-base v0.3.4. Fix #2

### LINKED ISSUE #2: Update to 0.3.4
https://github.com/deis/docker-base/pull/7 has merged but is not yet available on https://quay.io/repository/deis/base?tab=tags

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
@pmac r?

**Comment by pmac** [comment]
Doh! Review fail. The new tag at `deis/base` is `v0.3.4`. The build is failing at quay.io because the tag `0.3.4` doesn't exist :(

**Comment by pmac** [comment]
Fixed in 7c1e946d0581075fb7da6b00ebb6eadd214d7b45

**Comment by jgmize** [comment]
thanks, apologies for the typo.

**Pull request merged**
